blog/urls.py
from django.urls import path
from .views import (index, about, add_post,
                    post_list, post_detail, post_edit,
                    post_delete)

app_name = 'blog'
urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('posts/add/', add_post, name='add_post'),
    path('posts/', post_list, name='post_list'),
    path('posts/<slug:slug>/', post_detail, name='post_detail'),
    path('posts/<int:pk>/edit/', post_edit, name='post_edit'),
    path('posts/<int:pk>/delete/', post_delete, name='post_delete'),
]

myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from myblog import settings
from blog.views import root

urlpatterns = [
    path('', root),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('users/', include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "blog.views.forbidden"
handler404 = "blog.views.page_not_found"
handler500 = "blog.views.server_error"

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out,
                    user_detail, change_password)

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('detail/<int:pk>/', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
# from django.utils.text import slugify
from slugify import slugify

User = get_user_model()


class Post(models.Model):
    # author = models.CharField(max_length=50, verbose_name="Автор")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Текст поста")
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Опубликовано', editable=False)
    image = models.ImageField(upload_to='posts/', null=True, verbose_name='Изображение')
    slug = models.SlugField(max_length=200, unique=True, editable=False, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    class Meta:
        # имя таблицы в единств. числе
        verbose_name = "Пост"
        # имя таблицы во множеств. чисде
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

# class PostForm(forms.Form):
#     author = forms.CharField(max_length=50, label='Автор')
#     title = forms.CharField(max_length=200, label='Заголовок')
#     text = forms.CharField(label='Текст поста', widget=forms.Textarea())


class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        author = kwargs.pop('author', None)
        super(PostForm, self).__init__(*args, **kwargs)
        if author:
            self.fields['author'].initial = author
            self.fields['author'].disabled = True

    class Meta:
        model = Post
        fields = ['author', 'title', 'text', 'image']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .forms import PostForm
from .models import Post


"""
FBV - Function based views
CBV - Class based views
"""

def root(request):
    return render(request, template_name='blog/index.html')


def index(request):
    return render(request, template_name='blog/index.html')


def about(request):
    context = {
        "name": "Дмитрий",
        "lastname": "Горин",
        "email": "d.gorin@yandex.ru",
        "title": "О сайте"
    }
    return render(request, template_name='blog/about.html', context=context)


@login_required
def add_post(request):
    if request.method == "GET":
        form = PostForm(author=request.user)
        context = {
            'form': form,
            'title': 'Добавление поста'
        }
        return render(request, template_name='blog/add_post.html', context=context)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, author=request.user)
        if form.is_valid():
            form.save()

        return index(request)


def post_list(request):
    # получаем все объекты модели Post
    # сортируем по убыванию
    posts = Post.objects.all().order_by('-created_at')
    # показываем по 3 поста на странице
    paginator = Paginator(posts, 3)
    # получаем номер страницы из url
    page_number = request.GET.get('page')
    # получаем объекты для текущей страницы
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Посты',
        'page_obj': page_obj
    }
    return render(request, template_name='blog/posts.html', context=context)


def post_detail(request, slug):
    # получаем объект с заданным PK
    post = get_object_or_404(Post, slug=slug)
    context = {
        'title': 'Информация о посте',
        'post': post
    }
    return render(request, template_name='blog/post_detail.html', context=context)

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(data=request.POST, instance=post)
        if form.is_valid():
            form.save()
            return post_list(request)
    else:
        form = PostForm(instance=post)

    context = {
        'form': form,
        'title': "Редактировать пост"
    }
    return render(request, template_name="blog/post_edit.html", context=context)

@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect("blog:post_list")
    return render(request, template_name="blog/post_delete.html", context={'post': post})


def page_not_found(request, exception):
    return render(request, 'blog/404.html', status=404)


def forbidden(request, exception):
    return render(request, 'blog/403.html', status=403)


def server_error(request):
    return render(request, 'blog/500.html', status=500)

blog/templates/blog/501.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>501</title>
</head>
<body>
<h1>501</h1>
</body>
</html>

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Это HTML-страничка О сайте </h2>
<p>Автор - {{name}} {{lastname}}</p>
<p>Эл. Почта - {{email}}</p>
{% endblock content %}

blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Добавить новый пост</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать пост</button>
</form>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blog:index' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">Посты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Аккаунт
          </a>
          <ul class="dropdown-menu">
            {% if not user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
            <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
            <li><hr class="dropdown-divider"></li>
            {% endif %}
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
            <li><a class="dropdown-item" href="{% url 'users:detail' pk=user.pk %}">{{ user.username }}</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock content%}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>
    <a href="{% url 'blog:add_post' %}">Добавить новый пост</a>
</h2>

{% endblock content %}

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}

{% block content %}
<h2>Удалить пост?</h2>
<h3>Информация о посте № {{post.id}} </h3>
<hr>
<p>Автор - {{post.author}}</p>
<p>Название - {{post.title}}</p>
<p>Текст поста:</p>
<p>{{post.text}}</p>

{% if post.image %}
    <img width="300px" height="200px" src="{{post.image.url}}">
{% endif %}

<br>
<p>Создан: {{post.created_at}}</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger" >Удалить</button>
    <a href="{% url 'blog:post_list' %}">
        <button type="button" class="btn btn-primary">Отменить</button>
    </a>
</form>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Информация о посте № {{post.id}} </h2>
<hr>
<p>Автор - {{post.author}}</p>
<p>Название - {{post.title}}</p>
<p>Текст поста:</p>
<p>{{post.text}}</p>

{% if post.image %}
    <img width="300px" height="200px" src="{{post.image.url}}">
{% endif %}

<br>
<p>Создан: {{post.created_at}}</p>

<div>
    <a href="{% url 'blog:post_edit' pk=post.id %}" class="btn btn-primary">Редактировать</a>
    <form action="{% url 'blog:post_delete' pk=post.id %}" method="get" style="display:inline">
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
</div>

{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Редактировать пост</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Редактировать</button>
</form>
{% endblock content %}

blog/templates/blog/posts.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Список постов</h2>
{% for post in page_obj %}
    <h2>{{post.author}}: <a href="{{ post.get_absolute_url }}">{{post.title}}</a></h2>
    <p>{{post.text}}</p>
    <p>{{post.created_at}}</p>
    <br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя&raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock content %}